### ISSUE TITLE
divera_alarm sensor not working

### ISSUE THREAD

**Issue by dabenzel** [fwmarcel/home-assistant-divera#8] opened 2022-12-17 09:14 UTC
Hi,
I added your integration to HA.
Interestingly, the user_status is working correctly, but the divera_alarm sensor isn't.

I  the Logs, I get the following message:
```Logger: homeassistant.core
Source: core.py:1624
First occurred: 10:05:22 (2 occurrences)
Last logged: 10:08:59

Unable to remove unknown service divera/set_state
```

I use divera with two tenants (Einheiten). Is this maybe the Problem? The user status is from one tenant. 
![image](https://user-images.githubusercontent.com/2480235/208234817-75e8d2e8-5e0b-42bc-86d6-a8a9f3b54cf3.png)

**Comment by fwmarcel** [comment] 2022-12-17 09:36
Hello,
Indeed, I am not sure about that. But it could have to do with dual membership. I do not have this myself. Do I understand correctly that different statuses can be set for each unit?

Is there any other information in the log?

Greetings

**Comment by dabenzel** [comment] 2022-12-17 09:40
Hi,
yes. 


See attached:
Unit1: ![image](https://user-images.githubusercontent.com/2480235/208235719-bd93bb84-48da-4e63-9572-caf88912595b.png)
Unit 2: ![image](https://user-images.githubusercontent.com/2480235/208235727-f2377d44-74a1-4492-9d2b-6e645415635e.png)


Thats the whole log, filtered by "divera"
![image](https://user-images.githubusercontent.com/2480235/208235761-783b120f-b5f7-48c5-bef4-d2a87b5aae1f.png)

Added the integration yesterday and re-added it today, nearly 10:00h

**Comment by fwmarcel** [comment] 2022-12-17 13:50
In fact, I have not yet considered this possibility. I will have a closer look in the next few days. If necessary, I need feedback if the problem is then solved. 

Does the problem only affect the alarms or also the status?

**Comment by dabenzel** [comment] 2022-12-17 17:43
Hi,
alarm sensor not working at all.
Status sensor only shows the status of "unit 2" above (which was my first unit in my account) - but setting status works fine.

**Comment by fwmarcel** [comment] 2022-12-18 13:53
Hi
I have taken a quick look at the situation.
It definitely has nothing to do with the fact that multiple units are assigned to you. By default, the unit set in the settings is used. All further units are not supported so far. 
I could take this up as a feature request. However, I don't yet have a precise and simple idea of how this could be represented in Home Assistant.

The reason why the alarm sensor does not work must therefore be due to another cause. Interesting that you say that the status works. Especially, because in the log messages, it also looks to me rather like there would be connection problems.
Therefore the question: Is there currently an alarm in your unit 2 at all? If not, the Unknown status is desired.

**Comment by dabenzel** [comment] 2022-12-18 16:08
Hi, after changing my main unit, it works. 
(Did the test-alarm in unit 2, but my main unit was 1)
Status ist btw now from unit 2 too.


![image](https://user-images.githubusercontent.com/2480235/208307967-66c36058-042e-4ada-9385-0edc8d216e4f.png)

I think the Problem is on divera site as you don't have an api key per person per unit, but only per person.

**Comment by fwmarcel** [comment] 2022-12-18 16:30
hi
the integration works with the standard Divera API, which uses the default unit.
https://api.divera247.com/?urls.primaryName=api%2Fv2%2Fpull#/Daten/get_api_v2_pull_all
I will add an option to select the unit when adding the integration.

**Comment by dabenzel** [comment] 2022-12-18 16:33
Nice!
Would it also be possible to get the Lat/Lon of the alarm on the ha-map?

**Comment by fwmarcel** [comment] 2022-12-27 13:48
Would you be so kind to create a new issue for this?
in the best case with a description as detailed as possible, how you imagine the whole thing. 
 i will follow the development at this point and include this as a feature request.

**Comment by N1c093** [comment] 2023-01-12 10:43
> Thats the whole log, filtered by "divera" ![image](https://user-images.githubusercontent.com/2480235/208235761-783b120f-b5f7-48c5-bef4-d2a87b5aae1f.png)
> 

I also had the same timeout error some days ago. I noticed, that the configured timeout of the request is only 2 seconds.
I expand the timeout to 4 seconds and this solved my problem https://github.com/fwmarcel/home-assistant-divera/blob/9d1aafa253b4cae3ddd64532c82b68a998bd2e45/custom_components/divera/const.py#L17

@fwmarcel Is there any reason why the timeout is only 2 seconds? This seems to be pretty short for me.

**Comment by fwmarcel** [comment] 2023-01-13 14:21
Thanks for pointing this out. So far I did not experience the timeout error. I had set the timeout so that it worked for now. Accordingly, I had not thought about it so far. I consider the change soon.

**Closed** 2023-01-17 15:52 UTC
